package br.com.bsitecnologia.dashboard.model;

// Generated 15/09/2012 10:17:48 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import br.com.bsitecnologia.dashboard.util.BaseEntity;

/**
 * Alerta generated by hbm2java
 */
@Entity
@Table(name = "Alerta", catalog = "dashboard")
public class Alerta implements Serializable, BaseEntity {

	private static final long serialVersionUID = -8715694833906788752L;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private Integer id;
	
	@Column
	private String nome;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "status")
	private Status status;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "transicaoStatus")
	private TransicaoStatus transicaoStatus;
	
	@Column
	private Integer minutosDuracaoStatus;
	
	@Column
	private Integer minutosAntesDataPrevisaoConclusao;
	
	@Column
	private Integer minutosAntesDataFim;
	
	@Column
	private Integer corProjetoDashboard;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "alerta")
	private List<EmailTemplate> emailTemplates = new ArrayList<EmailTemplate>(0);
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "alerta")
	private List<AlertaProjeto> alertaProjetos = new ArrayList<AlertaProjeto>(0);

	
	public Alerta() {
	}

	public Alerta(Status status, TransicaoStatus transicaoStatus,
			Integer minutosDuracaoStatus,
			Integer minutosAntesDataPrevisaoConclusao,
			Integer minutosAntesDataFim, Integer corProjetoDashboard,
			List<EmailTemplate> emailTemplates,
			List<AlertaProjeto> alertaProjetos) {
		this.status = status;
		this.transicaoStatus = transicaoStatus;
		this.minutosDuracaoStatus = minutosDuracaoStatus;
		this.minutosAntesDataPrevisaoConclusao = minutosAntesDataPrevisaoConclusao;
		this.minutosAntesDataFim = minutosAntesDataFim;
		this.corProjetoDashboard = corProjetoDashboard;
		this.emailTemplates = emailTemplates;
		this.alertaProjetos = alertaProjetos;
	}
	
	@Override
	public Integer getId() {
		return this.id;
	}

	@Override
	public void setId(Integer id) {
		this.id = id;
	}

	public Status getStatus() {
		return this.status;
	}

	public void setStatus(Status status) {
		this.status = status;
	}

	public TransicaoStatus getTransicaoStatus() {
		return this.transicaoStatus;
	}

	public void setTransicaoStatus(TransicaoStatus transicaoStatus) {
		this.transicaoStatus = transicaoStatus;
	}

	public Integer getMinutosDuracaoStatus() {
		return this.minutosDuracaoStatus;
	}

	public void setMinutosDuracaoStatus(Integer minutosDuracaoStatus) {
		this.minutosDuracaoStatus = minutosDuracaoStatus;
	}

	public Integer getMinutosAntesDataPrevisaoConclusao() {
		return this.minutosAntesDataPrevisaoConclusao;
	}

	public void setMinutosAntesDataPrevisaoConclusao(
			Integer minutosAntesDataPrevisaoConclusao) {
		this.minutosAntesDataPrevisaoConclusao = minutosAntesDataPrevisaoConclusao;
	}

	public Integer getMinutosAntesDataFim() {
		return this.minutosAntesDataFim;
	}

	public void setMinutosAntesDataFim(Integer minutosAntesDataFim) {
		this.minutosAntesDataFim = minutosAntesDataFim;
	}

	public Integer getCorProjetoDashboard() {
		return this.corProjetoDashboard;
	}

	public void setCorProjetoDashboard(Integer corProjetoDashboard) {
		this.corProjetoDashboard = corProjetoDashboard;
	}

	public List<EmailTemplate> getEmailTemplates() {
		return this.emailTemplates;
	}

	public void setEmailTemplates(List<EmailTemplate> emailTemplates) {
		this.emailTemplates = emailTemplates;
	}

	public List<AlertaProjeto> getAlertaProjetos() {
		return this.alertaProjetos;
	}

	public void setAlertaProjetos(List<AlertaProjeto> alertaProjetos) {
		this.alertaProjetos = alertaProjetos;
	}
	
	public String getNome() {
		return nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Override
	public String getEntityDescription() {
		return nome;
	}
	
}
