package br.com.bsitecnologia.dashboard.model;

// Generated 15/09/2012 10:17:48 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import br.com.bsitecnologia.dashboard.util.BaseEntity;

/**
 * Artefato generated by hbm2java
 */
@Entity
@Table(name = "Artefato", catalog = "dashboard")
public class Artefato implements Serializable, BaseEntity {
	
	private static final long serialVersionUID = -1109314046100437153L;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private Integer id;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "colaboradorAtualizacao", nullable = false)
	private ColaboradorProjeto colaboradorAtualizacao;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "projeto", nullable = false)
	private Projeto projeto;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "colaboradorCriacao", nullable = false)
	private ColaboradorProjeto colaboradorCriacao;
	
	@Column(name = "nome", length = 100)
	private String nome;
	
	@Column(name = "path")
	private String path;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dataCriacao", length = 19)
	private Date dataCriacao;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dataAlteracao", length = 19)
	private Date dataAlteracao;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "artefato")
	private List<ComentarioArtefato> comentarioArtefatos = new ArrayList<ComentarioArtefato>(0);

	
	public Artefato() {
	}

	public Artefato(
			ColaboradorProjeto colaboradorAtualizacao,
			Projeto projeto, ColaboradorProjeto colaboradorCriacao) {
		this.colaboradorAtualizacao = colaboradorAtualizacao;
		this.projeto = projeto;
		this.colaboradorCriacao = colaboradorCriacao;
	}

	public Artefato(
			ColaboradorProjeto colaboradorAtualizacao,
			Projeto projeto, ColaboradorProjeto colaboradorCriacao,
			String nome, String path, Date dataCriacao, Date dataAlteracao,
			List<ComentarioArtefato> comentarioArtefatos) {
		this.colaboradorAtualizacao = colaboradorAtualizacao;
		this.projeto = projeto;
		this.colaboradorCriacao = colaboradorCriacao;
		this.nome = nome;
		this.path = path;
		this.dataCriacao = dataCriacao;
		this.dataAlteracao = dataAlteracao;
		this.comentarioArtefatos = comentarioArtefatos;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public ColaboradorProjeto getColaboradorAtualizacao() {
		return this.colaboradorAtualizacao;
	}

	public void setColaboradorAtualizacao(ColaboradorProjeto colaboradorAtualizacao) {
		this.colaboradorAtualizacao = colaboradorAtualizacao;
	}

	public Projeto getProjeto() {
		return this.projeto;
	}

	public void setProjeto(Projeto projeto) {
		this.projeto = projeto;
	}

	public ColaboradorProjeto getColaboradorProjetoByColaboradorCriacao() {
		return this.colaboradorCriacao;
	}

	public void setColaboradorCriacao(ColaboradorProjeto colaboradorCriacao) {
		this.colaboradorCriacao = colaboradorCriacao;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public String getPath() {
		return this.path;
	}

	public void setPath(String path) {
		this.path = path;
	}

	public Date getDataCriacao() {
		return this.dataCriacao;
	}

	public void setDataCriacao(Date dataCriacao) {
		this.dataCriacao = dataCriacao;
	}

	public Date getDataAlteracao() {
		return this.dataAlteracao;
	}

	public void setDataAlteracao(Date dataAlteracao) {
		this.dataAlteracao = dataAlteracao;
	}

	public List<ComentarioArtefato> getComentarioArtefatos() {
		return this.comentarioArtefatos;
	}

	public void setComentarioArtefatos(List<ComentarioArtefato> comentarioArtefatos) {
		this.comentarioArtefatos = comentarioArtefatos;
	}

	@Override
	public String getEntityDescription() {
		return getNome();
	}
	
}
