package br.com.bsitecnologia.dashboard.model;

// Generated 24/09/2012 20:18:49 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import br.com.bsitecnologia.dashboard.util.BaseEntity;

/**
 * AutorizacaoAtorExterno generated by hbm2java
 */
@Entity
@Table(name = "AutorizacaoAtorExterno", catalog = "dashboard")
public class AutorizacaoAtorExterno implements Serializable, BaseEntity {

	private static final long serialVersionUID = -2728317523951881610L;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private Integer id;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "projeto")
	private Projeto projeto;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "equipe")
	private Equipe equipe;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "funcionalidade", nullable = false)
	private Funcionalidade funcionalidade;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario", nullable = false)
	private Usuario usuario;

	public AutorizacaoAtorExterno() {
	}

	public AutorizacaoAtorExterno(Funcionalidade funcionalidade, Usuario usuario) {
		this.funcionalidade = funcionalidade;
		this.usuario = usuario;
	}

	public AutorizacaoAtorExterno(Projeto projeto, Equipe equipe, Funcionalidade funcionalidade, Usuario usuario) {
		this.projeto = projeto;
		this.equipe = equipe;
		this.funcionalidade = funcionalidade;
		this.usuario = usuario;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Projeto getProjeto() {
		return this.projeto;
	}

	public void setProjeto(Projeto projeto) {
		this.projeto = projeto;
	}

	public Equipe getEquipe() {
		return this.equipe;
	}

	public void setEquipe(Equipe equipe) {
		this.equipe = equipe;
	}

	public Funcionalidade getFuncionalidade() {
		return this.funcionalidade;
	}

	public void setFuncionalidade(Funcionalidade funcionalidade) {
		this.funcionalidade = funcionalidade;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Override
	public String getEntityDescription() {
		return String.format("AutorizacaoAtorExterno: id = %s", id);
	}

}
