package br.com.bsitecnologia.dashboard.model;

// Generated 15/09/2012 10:17:48 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import br.com.bsitecnologia.dashboard.util.BaseEntity;

/**
 * Cargo generated by hbm2java
 */
@Entity
@Table(name = "Cargo", catalog = "dashboard", uniqueConstraints = @UniqueConstraint(columnNames = "nome"))
public class Cargo implements Serializable, BaseEntity {
	
	private static final long serialVersionUID = 5187016459757319811L;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private Integer id;
	
	@Column(name = "nome", unique = true, length = 45)
	private String nome;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cargo")
	private List<Colaborador> colaboradores = new ArrayList<Colaborador>(0);
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cargo")
	private List<EmailTemplateColaboradores> emailTemplateColaboradores = new ArrayList<EmailTemplateColaboradores>(0);

	public Cargo() {
	}

	public Cargo(String nome, List<Colaborador> colaboradores,
			List<EmailTemplateColaboradores> emailTemplateColaboradores) {
		this.nome = nome;
		this.colaboradores = colaboradores;
		this.emailTemplateColaboradores = emailTemplateColaboradores;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public List<Colaborador> getColaboradores() {
		return this.colaboradores;
	}

	public void setColaboradors(List<Colaborador> colaboradores) {
		this.colaboradores = colaboradores;
	}

	public List<EmailTemplateColaboradores> getEmailTemplateColaboradores() {
		return this.emailTemplateColaboradores;
	}

	public void setEmailTemplateColaboradoreses(List<EmailTemplateColaboradores> emailTemplateColaboradores) {
		this.emailTemplateColaboradores = emailTemplateColaboradores;
	}

	@Override
	public String getEntityDescription() {
		return nome;
	}

}
