package br.com.bsitecnologia.dashboard.model;

// Generated 15/09/2012 10:17:48 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import br.com.bsitecnologia.dashboard.util.BaseEntity;

/**
 * Comentario generated by hbm2java
 */
@Entity
@Table(name = "Comentario", catalog = "dashboard")
public class Comentario implements Serializable, BaseEntity {
	
	private static final long serialVersionUID = 8203586872169582266L;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private Integer id;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "colaborador", nullable = false)
	private Colaborador colaborador;
	
	@Column(name = "texto", length = 2000)
	private String texto;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data", length = 19)
	private Date data;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "comentario")
	private List<ComentarioArtefato> comentarioArtefatos = new ArrayList<ComentarioArtefato>(0);
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "comentario")
	private List<ComentarioImpedimento> comentarioImpedimentos = new ArrayList<ComentarioImpedimento>(0);
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "comentario")
	private List<ComentarioProjeto> comentarioProjetos = new ArrayList<ComentarioProjeto>(0);
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "comentario")
	private List<ComentarioRiscoProjeto> comentarioRiscoProjetos = new ArrayList<ComentarioRiscoProjeto>(0);
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "comentario")
	private List<HistoricoRiscoProjeto> historicoRiscoProjetos = new ArrayList<HistoricoRiscoProjeto>(0);

	public Comentario() {
	}

	public Comentario(Colaborador colaborador) {
		this.colaborador = colaborador;
	}

	public Comentario(Colaborador colaborador, String texto, Date data,
			List<ComentarioArtefato> comentarioArtefatos,
			List<ComentarioImpedimento> comentarioImpedimentos,
			List<ComentarioProjeto> comentarioProjetos,
			List<ComentarioRiscoProjeto> comentarioRiscoProjetos,
			List<HistoricoRiscoProjeto> historicoRiscoProjetos) {
		this.colaborador = colaborador;
		this.texto = texto;
		this.data = data;
		this.comentarioArtefatos = comentarioArtefatos;
		this.comentarioImpedimentos = comentarioImpedimentos;
		this.comentarioProjetos = comentarioProjetos;
		this.comentarioRiscoProjetos = comentarioRiscoProjetos;
		this.historicoRiscoProjetos = historicoRiscoProjetos;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Colaborador getColaborador() {
		return this.colaborador;
	}

	public void setColaborador(Colaborador colaborador) {
		this.colaborador = colaborador;
	}

	public String getTexto() {
		return this.texto;
	}

	public void setTexto(String texto) {
		this.texto = texto;
	}

	public Date getData() {
		return this.data;
	}

	public void setData(Date data) {
		this.data = data;
	}

	public List<ComentarioArtefato> getComentarioArtefatos() {
		return this.comentarioArtefatos;
	}

	public void setComentarioArtefatos(List<ComentarioArtefato> comentarioArtefatos) {
		this.comentarioArtefatos = comentarioArtefatos;
	}

	public List<ComentarioImpedimento> getComentarioImpedimentos() {
		return this.comentarioImpedimentos;
	}

	public void setComentarioImpedimentos(List<ComentarioImpedimento> comentarioImpedimentos) {
		this.comentarioImpedimentos = comentarioImpedimentos;
	}

	public List<ComentarioProjeto> getComentarioProjetos() {
		return this.comentarioProjetos;
	}

	public void setComentarioProjetos(List<ComentarioProjeto> comentarioProjetos) {
		this.comentarioProjetos = comentarioProjetos;
	}

	public List<ComentarioRiscoProjeto> getComentarioRiscoProjetos() {
		return this.comentarioRiscoProjetos;
	}

	public void setComentarioRiscoProjetos(List<ComentarioRiscoProjeto> comentarioRiscoProjetos) {
		this.comentarioRiscoProjetos = comentarioRiscoProjetos;
	}

	public List<HistoricoRiscoProjeto> getHistoricoRiscoProjetos() {
		return this.historicoRiscoProjetos;
	}

	public void setHistoricoRiscoProjetos(List<HistoricoRiscoProjeto> historicoRiscoProjetos) {
		this.historicoRiscoProjetos = historicoRiscoProjetos;
	}
	
	@Override
	public String getEntityDescription() {
		return texto.substring(0, 20);
	}

}
