package br.com.bsitecnologia.dashboard.model;

// Generated 15/09/2012 10:17:48 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import br.com.bsitecnologia.dashboard.util.BaseEntity;

/**
 * ComentarioRiscoProjeto generated by hbm2java
 */
@Entity
@Table(name = "ComentarioRiscoProjeto", catalog = "dashboard")
public class ComentarioRiscoProjeto implements Serializable, BaseEntity {

	private static final long serialVersionUID = -5128042432218599067L;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private Integer id;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "riscoProjeto", nullable = false)
	private RiscoProjeto riscoProjeto;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "comentario", nullable = false)
	private Comentario comentario;

	public ComentarioRiscoProjeto() {
	}

	public ComentarioRiscoProjeto(RiscoProjeto riscoProjeto,
			Comentario comentario) {
		this.riscoProjeto = riscoProjeto;
		this.comentario = comentario;
	}

	
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public RiscoProjeto getRiscoProjeto() {
		return this.riscoProjeto;
	}

	public void setRiscoProjeto(RiscoProjeto riscoProjeto) {
		this.riscoProjeto = riscoProjeto;
	}

	public Comentario getComentario() {
		return this.comentario;
	}

	public void setComentario(Comentario comentario) {
		this.comentario = comentario;
	}
	
	@Override
	public String getEntityDescription() {
		return String.format("%s - %s", riscoProjeto.getRisco().getNome(), riscoProjeto.getProjeto().getNome());
	}

}
