package br.com.bsitecnologia.dashboard.model;

// Generated 15/09/2012 10:17:48 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import br.com.bsitecnologia.dashboard.util.BaseEntity;

/**
 * ComentarioImpedimento generated by hbm2java
 */
@Entity
@Table(name = "ComentarioImpedimento", catalog = "dashboard")
public class ComentarioImpedimento implements Serializable, BaseEntity {
	
	private static final long serialVersionUID = -3680046720727254898L;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private Integer id;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "impedimento", nullable = false)
	private Impedimento impedimento;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "comentario", nullable = false)
	private Comentario comentario;

	public ComentarioImpedimento() {
	}

	public ComentarioImpedimento(Impedimento impedimento, Comentario comentario) {
		this.impedimento = impedimento;
		this.comentario = comentario;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
	
	public Impedimento getImpedimento() {
		return this.impedimento;
	}

	public void setImpedimento(Impedimento impedimento) {
		this.impedimento = impedimento;
	}

	public Comentario getComentario() {
		return this.comentario;
	}

	public void setComentario(Comentario comentario) {
		this.comentario = comentario;
	}
	
	public String getEntityDescription() {
		return String.format("%s - %s", impedimento.getNome(),  comentario.getTexto().substring(0, 20));
	}

}
