package br.com.bsitecnologia.dashboard.model;

// Generated 15/09/2012 10:17:48 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import br.com.bsitecnologia.dashboard.util.BaseEntity;

/**
 * EquipeProjeto generated by hbm2java
 */
@Entity
@Table(name = "EquipeProjeto", catalog = "dashboard")
public class EquipeProjeto implements Serializable, BaseEntity {
	
	private static final long serialVersionUID = -8985947394376998159L;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private Integer id;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "projeto", nullable = false)
	private Projeto projeto;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "equipe", nullable = false)
	private Equipe equipe;

	public EquipeProjeto() {
	}

	public EquipeProjeto(Projeto projeto, Equipe equipe) {
		this.projeto = projeto;
		this.equipe = equipe;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Projeto getProjeto() {
		return this.projeto;
	}

	public void setProjeto(Projeto projeto) {
		this.projeto = projeto;
	}

	public Equipe getEquipe() {
		return this.equipe;
	}

	public void setEquipe(Equipe equipe) {
		this.equipe = equipe;
	}

	@Override
	public String getEntityDescription() {
		return String.format("%s - %s", equipe.getNome(), projeto.getNome());
	}

}
