package br.com.bsitecnologia.dashboard.model;

// Generated 15/09/2012 10:17:48 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import br.com.bsitecnologia.dashboard.util.BaseEntity;

/**
 * Equipe generated by hbm2java
 */
@Entity
@Table(name = "Equipe", catalog = "dashboard", uniqueConstraints = @UniqueConstraint(columnNames = "nome"))
public class Equipe implements Serializable, BaseEntity {
	
	private static final long serialVersionUID = 4149797338437888179L;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private Integer id;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "equipePai")
	private Equipe equipePai;
	
	@Column(name = "nome", unique = true, nullable = false, length = 45)
	private String nome;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "equipePai")
	private Set<Equipe> equipes = new HashSet<Equipe>(0);
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "equipe")
	private Set<EmailTemplateColaboradores> emailTemplateColaboradores = new HashSet<EmailTemplateColaboradores>(0);
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "equipe")
	private Set<EquipeProjeto> equipeProjetos = new HashSet<EquipeProjeto>(0);
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "equipe")
	private Set<Colaborador> colaboradores = new HashSet<Colaborador>(0);

	public Equipe() {
	}

	public Equipe(String nome) {
		this.nome = nome;
	}

	public Equipe(Integer id, Equipe equipePai, String nome,
			Set<Equipe> equipes,
			Set<EmailTemplateColaboradores> emailTemplateColaboradores,
			Set<EquipeProjeto> equipeProjetos, Set<Colaborador> colaboradores) {
		this.id = id;
		this.equipePai = equipePai;
		this.nome = nome;
		this.equipes = equipes;
		this.emailTemplateColaboradores = emailTemplateColaboradores;
		this.equipeProjetos = equipeProjetos;
		this.colaboradores = colaboradores;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Equipe getEquipePai() {
		return equipePai;
	}

	public void setEquipePai(Equipe equipePai) {
		this.equipePai = equipePai;
	}

	public String getNome() {
		return nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public Set<Equipe> getEquipes() {
		return equipes;
	}

	public void setEquipes(Set<Equipe> equipes) {
		this.equipes = equipes;
	}

	public Set<EmailTemplateColaboradores> getEmailTemplateColaboradores() {
		return emailTemplateColaboradores;
	}

	public void setEmailTemplateColaboradores(
			Set<EmailTemplateColaboradores> emailTemplateColaboradores) {
		this.emailTemplateColaboradores = emailTemplateColaboradores;
	}

	public Set<EquipeProjeto> getEquipeProjetos() {
		return equipeProjetos;
	}

	public void setEquipeProjetos(Set<EquipeProjeto> equipeProjetos) {
		this.equipeProjetos = equipeProjetos;
	}

	public Set<Colaborador> getColaboradores() {
		return colaboradores;
	}

	public void setColaboradores(Set<Colaborador> colaboradores) {
		this.colaboradores = colaboradores;
	}

	@Override
	public String getEntityDescription() {
		return nome;
	}

}
