package br.com.bsitecnologia.dashboard.model;

// Generated 15/09/2012 10:17:48 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import br.com.bsitecnologia.dashboard.util.BaseEntity;

/**
 * HistoricoRiscoProjeto generated by hbm2java
 */
@Entity
@Table(name = "HistoricoRiscoProjeto", catalog = "dashboard")
public class HistoricoRiscoProjeto implements Serializable, BaseEntity {
	
	private static final long serialVersionUID = 6138627686094607489L;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private Integer id;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "riscoProjeto", nullable = false)
	private RiscoProjeto riscoProjeto;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "colaborador", nullable = false)
	private Colaborador colaborador;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "impacto", nullable = false)
	private Impacto impacto;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "comentario", nullable = false)
	private Comentario comentario;
	
	@Column(name = "probabilidade", nullable = false, length = 45)
	private String probabilidade;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dataAlteracao", nullable = false, length = 19)
	private Date dataAlteracao;

	public HistoricoRiscoProjeto() {
	}

	public HistoricoRiscoProjeto(RiscoProjeto riscoProjeto,
			Colaborador colaborador, Impacto impacto, Comentario comentario,
			String probabilidade, Date dataAlteracao) {
		this.riscoProjeto = riscoProjeto;
		this.colaborador = colaborador;
		this.impacto = impacto;
		this.comentario = comentario;
		this.probabilidade = probabilidade;
		this.dataAlteracao = dataAlteracao;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public RiscoProjeto getRiscoProjeto() {
		return this.riscoProjeto;
	}

	public void setRiscoProjeto(RiscoProjeto riscoProjeto) {
		this.riscoProjeto = riscoProjeto;
	}

	public Colaborador getColaborador() {
		return this.colaborador;
	}

	public void setColaborador(Colaborador colaborador) {
		this.colaborador = colaborador;
	}

	public Impacto getImpacto() {
		return this.impacto;
	}

	public void setImpacto(Impacto impacto) {
		this.impacto = impacto;
	}

	public Comentario getComentario() {
		return this.comentario;
	}

	public void setComentario(Comentario comentario) {
		this.comentario = comentario;
	}

	public String getProbabilidade() {
		return this.probabilidade;
	}

	public void setProbabilidade(String probabilidade) {
		this.probabilidade = probabilidade;
	}

	public Date getDataAlteracao() {
		return this.dataAlteracao;
	}

	public void setDataAlteracao(Date dataAlteracao) {
		this.dataAlteracao = dataAlteracao;
	}

	@Override
	public String getEntityDescription() {
		return String.format("Histórico risco projeto: %s - %s", riscoProjeto.getRisco().getNome(), riscoProjeto.getProjeto().getNome());
	}
	
}
