package br.com.bsitecnologia.dashboard.model;

// Generated 15/09/2012 10:17:48 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import br.com.bsitecnologia.dashboard.util.BaseEntity;

/**
 * HistoricoProjeto generated by hbm2java
 */
@Entity
@Table(name = "HistoricoProjeto", catalog = "dashboard")
public class HistoricoProjeto implements Serializable, BaseEntity {
	
	private static final long serialVersionUID = -6912670534509578891L;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private Integer id;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "projeto", nullable = false)
	private Projeto projeto;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "transicaoStatus", nullable = false)
	private TransicaoStatus transicaoStatus;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "colaborador", nullable = false)
	private Colaborador colaborador;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "atorExternoTransicaoStatus")
	private AtorExternoTransicaoStatus atorExternoTransicaoStatus;
	
	@Temporal(TemporalType.DATE)
	@Column(name = "dataInicio", length = 10)
	private Date dataInicio;
	
	@Temporal(TemporalType.DATE)
	@Column(name = "dataFim", length = 10)
	private Date dataFim;
	
	@Temporal(TemporalType.DATE)
	@Column(name = "dataPrevisaoConclusao", length = 10)
	private Date dataPrevisaoConclusao;
	
	@Column(name = "orcamento", precision = 11)
	private BigDecimal orcamento;
	
	@Column(name = "custo", precision = 11)
	private BigDecimal custo;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dataAlteracao", length = 19)
	private Date dataAlteracao;

	public HistoricoProjeto() {
	}

	public HistoricoProjeto(Projeto projeto, TransicaoStatus transicaoStatus,
			Colaborador colaborador) {
		this.projeto = projeto;
		this.transicaoStatus = transicaoStatus;
		this.colaborador = colaborador;
	}

	public HistoricoProjeto(Projeto projeto, TransicaoStatus transicaoStatus,
			Colaborador colaborador,
			AtorExternoTransicaoStatus atorExternoTransicaoStatus,
			Date dataInicio, Date dataFim, Date dataPrevisaoConclusao,
			BigDecimal orcamento, BigDecimal custo, Date dataAlteracao) {
		this.projeto = projeto;
		this.transicaoStatus = transicaoStatus;
		this.colaborador = colaborador;
		this.atorExternoTransicaoStatus = atorExternoTransicaoStatus;
		this.dataInicio = dataInicio;
		this.dataFim = dataFim;
		this.dataPrevisaoConclusao = dataPrevisaoConclusao;
		this.orcamento = orcamento;
		this.custo = custo;
		this.dataAlteracao = dataAlteracao;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Projeto getProjeto() {
		return this.projeto;
	}

	public void setProjeto(Projeto projeto) {
		this.projeto = projeto;
	}

	public TransicaoStatus getTransicaoStatus() {
		return this.transicaoStatus;
	}

	public void setTransicaoStatus(TransicaoStatus transicaoStatus) {
		this.transicaoStatus = transicaoStatus;
	}

	public Colaborador getColaborador() {
		return this.colaborador;
	}

	public void setColaborador(Colaborador colaborador) {
		this.colaborador = colaborador;
	}

	public AtorExternoTransicaoStatus getAtorExternoTransicaoStatus() {
		return this.atorExternoTransicaoStatus;
	}

	public void setAtorExternoTransicaoStatus(
			AtorExternoTransicaoStatus atorExternoTransicaoStatus) {
		this.atorExternoTransicaoStatus = atorExternoTransicaoStatus;
	}

	public Date getDataInicio() {
		return this.dataInicio;
	}

	public void setDataInicio(Date dataInicio) {
		this.dataInicio = dataInicio;
	}

	public Date getDataFim() {
		return this.dataFim;
	}

	public void setDataFim(Date dataFim) {
		this.dataFim = dataFim;
	}

	public Date getDataPrevisaoConclusao() {
		return this.dataPrevisaoConclusao;
	}

	public void setDataPrevisaoConclusao(Date dataPrevisaoConclusao) {
		this.dataPrevisaoConclusao = dataPrevisaoConclusao;
	}

	public BigDecimal getOrcamento() {
		return this.orcamento;
	}

	public void setOrcamento(BigDecimal orcamento) {
		this.orcamento = orcamento;
	}

	public BigDecimal getCusto() {
		return this.custo;
	}

	public void setCusto(BigDecimal custo) {
		this.custo = custo;
	}

	public Date getDataAlteracao() {
		return this.dataAlteracao;
	}

	public void setDataAlteracao(Date dataAlteracao) {
		this.dataAlteracao = dataAlteracao;
	}

	@Override
	public String getEntityDescription() {
		return String.format("Historico projeto: %s", projeto.getNome());
	}

}
