package br.com.bsitecnologia.dashboard.model;

// Generated 15/09/2012 10:17:48 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import br.com.bsitecnologia.dashboard.util.BaseEntity;

/**
 * Impacto generated by hbm2java
 */
@Entity
@Table(name = "Impacto", catalog = "dashboard")
public class Impacto implements Serializable, BaseEntity {
	
	private static final long serialVersionUID = -7228461449602418094L;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private Integer id;
	
	@Column(name = "descricao", length = 128)
	private String descricao;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "impacto")
	private List<Risco> riscos = new ArrayList<Risco>(0);
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "impacto")
	private List<HistoricoRiscoProjeto> historicoRiscoProjetos = new ArrayList<HistoricoRiscoProjeto>(0);

	public Impacto() {
	}

	public Impacto(String descricao, List<Risco> riscos,
			List<HistoricoRiscoProjeto> historicoRiscoProjetos) {
		this.descricao = descricao;
		this.riscos = riscos;
		this.historicoRiscoProjetos = historicoRiscoProjetos;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	public List<Risco> getRiscos() {
		return this.riscos;
	}

	public void setRiscos(List<Risco> riscos) {
		this.riscos = riscos;
	}

	public List<HistoricoRiscoProjeto> getHistoricoRiscoProjetos() {
		return this.historicoRiscoProjetos;
	}

	public void setHistoricoRiscoProjetos(List<HistoricoRiscoProjeto> historicoRiscoProjetos) {
		this.historicoRiscoProjetos = historicoRiscoProjetos;
	}

	@Override
	public String getEntityDescription() {
		return descricao;
	}

}
