package br.com.bsitecnologia.dashboard.model;

// Generated 15/09/2012 10:17:48 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import br.com.bsitecnologia.dashboard.util.BaseEntity;

/**
 * Impedimento generated by hbm2java
 */
@Entity
@Table(name = "Impedimento", catalog = "dashboard")
public class Impedimento implements Serializable, BaseEntity {

	private static final long serialVersionUID = -7643301864424870162L;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private Integer id;
	
	@Column(length=100)
	private String nome;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "colaboradorAutor", nullable = false)
	private Colaborador colaboradorAutor;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "atorExterno")
	private AtorExterno atorExterno;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "projeto", nullable = false)
	private Projeto projeto;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "colaboradorImpedimento")
	private Colaborador colaboradorAtribuido;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "risco")
	private Risco risco;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dataInicio", nullable = false, length = 19)
	private Date dataInicio;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dataFim", length = 19)
	private Date dataFim;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "impedimento")
	private List<ComentarioImpedimento> comentarioImpedimentos = new ArrayList<ComentarioImpedimento>(0);

	public Impedimento() {
	}
	
	public Impedimento(Integer id, Colaborador colaboradorAutor,
			AtorExterno atorExterno, Projeto projeto,
			Colaborador colaboradorAtribuido, Risco risco, Date dataInicio,
			Date dataFim, List<ComentarioImpedimento> comentarioImpedimentos) {
		this.id = id;
		this.colaboradorAutor = colaboradorAutor;
		this.atorExterno = atorExterno;
		this.projeto = projeto;
		this.colaboradorAtribuido = colaboradorAtribuido;
		this.risco = risco;
		this.dataInicio = dataInicio;
		this.dataFim = dataFim;
		this.comentarioImpedimentos = comentarioImpedimentos;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
	
	public String getNome() {
		return nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public Colaborador getColaboradorAutor() {
		return colaboradorAutor;
	}

	public void setColaboradorAutor(Colaborador colaboradorAutor) {
		this.colaboradorAutor = colaboradorAutor;
	}

	public AtorExterno getAtorExterno() {
		return atorExterno;
	}

	public void setAtorExterno(AtorExterno atorExterno) {
		this.atorExterno = atorExterno;
	}

	public Projeto getProjeto() {
		return projeto;
	}

	public void setProjeto(Projeto projeto) {
		this.projeto = projeto;
	}

	public Colaborador getColaboradorAtribuido() {
		return colaboradorAtribuido;
	}

	public void setColaboradorAtribuido(Colaborador colaboradorAtribuido) {
		this.colaboradorAtribuido = colaboradorAtribuido;
	}

	public Risco getRisco() {
		return risco;
	}

	public void setRisco(Risco risco) {
		this.risco = risco;
	}

	public Date getDataInicio() {
		return dataInicio;
	}

	public void setDataInicio(Date dataInicio) {
		this.dataInicio = dataInicio;
	}

	public Date getDataFim() {
		return dataFim;
	}

	public void setDataFim(Date dataFim) {
		this.dataFim = dataFim;
	}

	public List<ComentarioImpedimento> getComentarioImpedimentos() {
		return comentarioImpedimentos;
	}

	public void setComentarioImpedimentos(List<ComentarioImpedimento> comentarioImpedimentos) {
		this.comentarioImpedimentos = comentarioImpedimentos;
	}

	@Override
	public String getEntityDescription() {
		return nome;
	}

}
