package br.com.bsitecnologia.dashboard.model;

// Generated 15/09/2012 10:17:48 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import br.com.bsitecnologia.dashboard.util.BaseEntity;

/**
 * Projeto generated by hbm2java
 */
@Entity
@Table(name = "Projeto", catalog = "dashboard", uniqueConstraints = @UniqueConstraint(columnNames = "nome"))
public class Projeto implements Serializable, BaseEntity {
	
	private static final long serialVersionUID = -322801059633037259L;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private Integer id;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "projetoPai")
	private Projeto projetoPai;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "status", nullable = false)
	private Status status;
	
	@Column(name = "nome", unique = true, nullable = false, length = 45)
	private String nome;
	
	@Temporal(TemporalType.DATE)
	@Column(name = "dataInicio", length = 10)
	private Date dataInicio;
	
	@Temporal(TemporalType.DATE)
	@Column(name = "dataFim", length = 10)
	private Date dataFim;
	
	@Temporal(TemporalType.DATE)
	@Column(name = "dataPrevisaoConclusao", length = 10)
	private Date dataPrevisaoConclusao;
	
	@Column(name = "orcamento", precision = 11)
	private BigDecimal orcamento;
	
	@Column(name = "custo", precision = 11)
	private BigDecimal custo;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "projeto")
	private List<HistoricoProjeto> historicoProjetos = new ArrayList<HistoricoProjeto>(0);
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "projeto")
	private List<AtorExternoTransicaoStatus> atorExternoTransicaoStatuses = new ArrayList<AtorExternoTransicaoStatus>(0);
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "projeto")
	private List<ComentarioProjeto> comentarioProjetos = new ArrayList<ComentarioProjeto>(0);
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "projeto")
	private List<ColaboradorProjeto> colaboradorProjetos = new ArrayList<ColaboradorProjeto>(0);
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "projeto")
	private List<RiscoProjeto> riscoProjetos = new ArrayList<RiscoProjeto>(0);
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "projeto")
	private List<EquipeProjeto> equipeProjetos = new ArrayList<EquipeProjeto>(0);
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "projeto")
	private List<AlertaProjeto> alertaProjetos = new ArrayList<AlertaProjeto>(0);
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "projeto")
	private List<Artefato> artefatos = new ArrayList<Artefato>(0);
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "projetoPai")
	private List<Projeto> projetosFilhos = new ArrayList<Projeto>(0);
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "projeto")
	private List<Impedimento> impedimentos = new ArrayList<Impedimento>(0);
	
	@OneToMany(fetch=FetchType.LAZY, mappedBy="projeto")
    private List<AutorizacaoColaborador> autorizacoesColaboradores = new ArrayList<AutorizacaoColaborador>(0);
    
	@OneToMany(fetch=FetchType.LAZY, mappedBy="projeto")
    private List<AutorizacaoAtorExterno> autorizacoesAtorExternos = new ArrayList<AutorizacaoAtorExterno>(0);

	
	public Projeto() {
	}

	public Projeto(Status status, String nome) {
		this.status = status;
		this.nome = nome;
	}
	
	public Projeto(Integer id, Projeto projetoPai, Status status, String nome,
			Date dataInicio, Date dataFim, Date dataPrevisaoConclusao,
			BigDecimal orcamento, BigDecimal custo,
			List<HistoricoProjeto> historicoProjetos,
			List<AtorExternoTransicaoStatus> atorExternoTransicaoStatuses,
			List<ComentarioProjeto> comentarioProjetos,
			List<ColaboradorProjeto> colaboradorProjetos,
			List<RiscoProjeto> riscoProjetos, List<EquipeProjeto> equipeProjetos,
			List<AlertaProjeto> alertaProjetos, List<Artefato> artefatos,
			List<Projeto> projetosFilhos, List<Impedimento> impedimentos) {
		this.id = id;
		this.projetoPai = projetoPai;
		this.status = status;
		this.nome = nome;
		this.dataInicio = dataInicio;
		this.dataFim = dataFim;
		this.dataPrevisaoConclusao = dataPrevisaoConclusao;
		this.orcamento = orcamento;
		this.custo = custo;
		this.historicoProjetos = historicoProjetos;
		this.atorExternoTransicaoStatuses = atorExternoTransicaoStatuses;
		this.comentarioProjetos = comentarioProjetos;
		this.colaboradorProjetos = colaboradorProjetos;
		this.riscoProjetos = riscoProjetos;
		this.equipeProjetos = equipeProjetos;
		this.alertaProjetos = alertaProjetos;
		this.artefatos = artefatos;
		this.projetosFilhos = projetosFilhos;
		this.impedimentos = impedimentos;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Projeto getProjetoPai() {
		return projetoPai;
	}

	public void setProjetoPai(Projeto projetoPai) {
		this.projetoPai = projetoPai;
	}

	public Status getStatus() {
		return status;
	}

	public void setStatus(Status status) {
		this.status = status;
	}

	public String getNome() {
		return nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public Date getDataInicio() {
		return dataInicio;
	}

	public void setDataInicio(Date dataInicio) {
		this.dataInicio = dataInicio;
	}

	public Date getDataFim() {
		return dataFim;
	}

	public void setDataFim(Date dataFim) {
		this.dataFim = dataFim;
	}

	public Date getDataPrevisaoConclusao() {
		return dataPrevisaoConclusao;
	}

	public void setDataPrevisaoConclusao(Date dataPrevisaoConclusao) {
		this.dataPrevisaoConclusao = dataPrevisaoConclusao;
	}

	public BigDecimal getOrcamento() {
		return orcamento;
	}

	public void setOrcamento(BigDecimal orcamento) {
		this.orcamento = orcamento;
	}

	public BigDecimal getCusto() {
		return custo;
	}

	public void setCusto(BigDecimal custo) {
		this.custo = custo;
	}

	public List<HistoricoProjeto> getHistoricoProjetos() {
		return historicoProjetos;
	}

	public void setHistoricoProjetos(List<HistoricoProjeto> historicoProjetos) {
		this.historicoProjetos = historicoProjetos;
	}

	public List<AtorExternoTransicaoStatus> getAtorExternoTransicaoStatuses() {
		return atorExternoTransicaoStatuses;
	}

	public void setAtorExternoTransicaoStatuses(
			List<AtorExternoTransicaoStatus> atorExternoTransicaoStatuses) {
		this.atorExternoTransicaoStatuses = atorExternoTransicaoStatuses;
	}

	public List<ComentarioProjeto> getComentarioProjetos() {
		return comentarioProjetos;
	}

	public void setComentarioProjetos(List<ComentarioProjeto> comentarioProjetos) {
		this.comentarioProjetos = comentarioProjetos;
	}

	public List<ColaboradorProjeto> getColaboradorProjetos() {
		return colaboradorProjetos;
	}

	public void setColaboradorProjetos(List<ColaboradorProjeto> colaboradorProjetos) {
		this.colaboradorProjetos = colaboradorProjetos;
	}

	public List<RiscoProjeto> getRiscoProjetos() {
		return riscoProjetos;
	}

	public void setRiscoProjetos(List<RiscoProjeto> riscoProjetos) {
		this.riscoProjetos = riscoProjetos;
	}

	public List<EquipeProjeto> getEquipeProjetos() {
		return equipeProjetos;
	}

	public void setEquipeProjetos(List<EquipeProjeto> equipeProjetos) {
		this.equipeProjetos = equipeProjetos;
	}

	public List<AlertaProjeto> getAlertaProjetos() {
		return alertaProjetos;
	}

	public void setAlertaProjetos(List<AlertaProjeto> alertaProjetos) {
		this.alertaProjetos = alertaProjetos;
	}

	public List<Artefato> getArtefatos() {
		return artefatos;
	}

	public void setArtefatos(List<Artefato> artefatos) {
		this.artefatos = artefatos;
	}

	public List<Projeto> getProjetosFilhos() {
		return projetosFilhos;
	}

	public void setProjetosFilhos(List<Projeto> projetosFilhos) {
		this.projetosFilhos = projetosFilhos;
	}

	public List<Impedimento> getImpedimentos() {
		return impedimentos;
	}

	public void setImpedimentos(List<Impedimento> impedimentos) {
		this.impedimentos = impedimentos;
	}
	
	public List<AutorizacaoColaborador> getAutorizacoesColaboradores() {
		return autorizacoesColaboradores;
	}

	public void setAutorizacoesColaboradores(
			List<AutorizacaoColaborador> autorizacoesColaboradores) {
		this.autorizacoesColaboradores = autorizacoesColaboradores;
	}

	public List<AutorizacaoAtorExterno> getAutorizacoesAtorExternos() {
		return autorizacoesAtorExternos;
	}

	public void setAutorizacoesAtorExternos(
			List<AutorizacaoAtorExterno> autorizacoesAtorExternos) {
		this.autorizacoesAtorExternos = autorizacoesAtorExternos;
	}

	@Override
	public String getEntityDescription() {
		return nome;
	}
}
