package br.com.bsitecnologia.dashboard.model;

// Generated 15/09/2012 10:17:48 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import br.com.bsitecnologia.dashboard.util.BaseEntity;

/**
 * RiscoProjeto generated by hbm2java
 */
@Entity
@Table(name = "RiscoProjeto", catalog = "dashboard")
public class RiscoProjeto implements Serializable, BaseEntity {

	private static final long serialVersionUID = 657798031449335353L;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private Integer id;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "projeto", nullable = false)
	private Projeto projeto;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "risco", nullable = false)
	private Risco risco;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "riscoProjeto")
	private List<ComentarioRiscoProjeto> comentarioRiscoProjetos = new ArrayList<ComentarioRiscoProjeto>(0);
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "riscoProjeto")
	private List<HistoricoRiscoProjeto> historicoRiscoProjetos = new ArrayList<HistoricoRiscoProjeto>(0);

	public RiscoProjeto() {
	}

	public RiscoProjeto(Projeto projeto, Risco risco) {
		this.projeto = projeto;
		this.risco = risco;
	}

	public RiscoProjeto(Projeto projeto, Risco risco,
			List<ComentarioRiscoProjeto> comentarioRiscoProjetos,
			List<HistoricoRiscoProjeto> historicoRiscoProjetos) {
		this.projeto = projeto;
		this.risco = risco;
		this.comentarioRiscoProjetos = comentarioRiscoProjetos;
		this.historicoRiscoProjetos = historicoRiscoProjetos;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Projeto getProjeto() {
		return this.projeto;
	}

	public void setProjeto(Projeto projeto) {
		this.projeto = projeto;
	}

	public Risco getRisco() {
		return this.risco;
	}

	public void setRisco(Risco risco) {
		this.risco = risco;
	}

	public List<ComentarioRiscoProjeto> getComentarioRiscoProjetos() {
		return this.comentarioRiscoProjetos;
	}

	public void setComentarioRiscoProjetos(List<ComentarioRiscoProjeto> comentarioRiscoProjetos) {
		this.comentarioRiscoProjetos = comentarioRiscoProjetos;
	}

	public List<HistoricoRiscoProjeto> getHistoricoRiscoProjetos() {
		return this.historicoRiscoProjetos;
	}

	public void setHistoricoRiscoProjetos(List<HistoricoRiscoProjeto> historicoRiscoProjetos) {
		this.historicoRiscoProjetos = historicoRiscoProjetos;
	}

	@Override
	public String getEntityDescription() {
		return String.format("%s - %s", risco.getNome(), projeto.getNome());
	}

}
