package br.com.bsitecnologia.dashboard.model;

// Generated 15/09/2012 10:17:48 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import br.com.bsitecnologia.dashboard.util.BaseEntity;

/**
 * TransicaoStatus generated by hbm2java
 */
@Entity
@Table(name = "TransicaoStatus", catalog = "dashboard", uniqueConstraints = @UniqueConstraint(columnNames = "nome"))
public class TransicaoStatus implements Serializable, BaseEntity {
	
	private static final long serialVersionUID = -553743027231825948L;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private Integer id;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "statusTo", nullable = false)
	private Status statusTo;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "statusFrom", nullable = false)
	private Status statusFrom;
	
	@Column(name = "nome", unique = true, length = 45)
	private String nome;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "transicaoStatus")
	private List<AtorExternoTransicaoStatus> atorExternoTransicaoStatus = new ArrayList<AtorExternoTransicaoStatus>(0);
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "transicaoStatus")
	private List<Alerta> alertas = new ArrayList<Alerta>(0);
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "transicaoStatus")
	private List<HistoricoProjeto> historicoProjetos = new ArrayList<HistoricoProjeto>(0);

	public TransicaoStatus() {
	}

	public TransicaoStatus(Status statusTo, Status statusFrom) {
		this.statusTo = statusTo;
		this.statusFrom = statusFrom;
	}
	
	public TransicaoStatus(Status statusTo, Status statusFrom, String nome,
			List<AtorExternoTransicaoStatus> atorExternoTransicaoStatus,
			List<Alerta> alertas, List<HistoricoProjeto> historicoProjetos) {
		this.statusTo = statusTo;
		this.statusFrom = statusFrom;
		this.nome = nome;
		this.atorExternoTransicaoStatus = atorExternoTransicaoStatus;
		this.alertas = alertas;
		this.historicoProjetos = historicoProjetos;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Status getStatusTo() {
		return statusTo;
	}

	public void setStatusTo(Status statusTo) {
		this.statusTo = statusTo;
	}

	public Status getStatusFrom() {
		return statusFrom;
	}

	public void setStatusFrom(Status statusFrom) {
		this.statusFrom = statusFrom;
	}

	public String getNome() {
		return nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public List<AtorExternoTransicaoStatus> getAtorExternoTransicaoStatus() {
		return atorExternoTransicaoStatus;
	}

	public void setAtorExternoTransicaoStatus(
			List<AtorExternoTransicaoStatus> atorExternoTransicaoStatus) {
		this.atorExternoTransicaoStatus = atorExternoTransicaoStatus;
	}

	public List<Alerta> getAlertas() {
		return alertas;
	}

	public void setAlertas(List<Alerta> alertas) {
		this.alertas = alertas;
	}

	public List<HistoricoProjeto> getHistoricoProjetos() {
		return historicoProjetos;
	}

	public void setHistoricoProjetos(List<HistoricoProjeto> historicoProjetos) {
		this.historicoProjetos = historicoProjetos;
	}

	@Override
	public String getEntityDescription() {
		return nome;
	}

}
